### PR TITLE
Debian: fix source package issues and add lintian-overrides

### PR DESCRIPTION
**Pull request by darealshinji**
Overriding the following warnings (including explanations):
```
wine-staging-amd64 binary: statically-linked-binary opt/wine-staging/bin/wine64-preloader
wine-staging-i386 binary: statically-linked-binary opt/wine-staging/bin/wine-preloader
wine-staging source: quilt-build-dep-but-no-series-file
```

And fixing these:
```
E: wine-staging source: build-depends-on-essential-package-without-using-version build-depends: coreutils
E: wine-staging source: build-depends-on-essential-package-without-using-version build-depends: gzip
W: wine-staging source: ancient-standards-version 3.9.2 (current is 3.9.5)
W: wine-staging source: patch-system-but-no-source-readme
```

### CODE REVIEW

**Comment by slackner** [comment]
compiles fine on our builders. @DarkPlayer: opinions? ^^

**Comment by DarkPlayer** [comment]
If "Standards-Version: 3.9.5" still works with all our debian targets, then I am fine with the changes.

**Comment by compholio** [comment]
@DarkPlayer: I've never had a problem with version mis-matches, it mostly seems to affect lintian warnings/errors.

**Comment by slackner** [comment]
I've merged the first four commits, they were added in https://github.com/wine-compholio/wine-staging/commit/e6884fe33471c152f3d994bbaf17ef63d3322d74. (Unfortunately Github doesn't recognize them because patch 5 is missing :/ )

I've left out the last one because its actually not true that we depend on `quilt` itself. It was required in an earlier version of the package, but currently we only need a couple of commandline tools. Its probably better to list them separately and avoid the dependency to `quilt` completely. I've removed it, but we'll have to test in a clean environment if any additional dependencies are missing now.

**Pull request closed without merging**
