### PR TITLE
Debian packaging

### PR DESCRIPTION
**Pull request by darealshinji**
Some Debian packaging fixes.

```
W: wine-staging-i386: control-file-is-empty conffiles
```
Deleted `conffiles` files.

```
E: wine-staging-i386: statically-linked-binary opt/wine-staging/bin/wine-preloader
E: wine-staging-amd64: statically-linked-binary opt/wine-staging/bin/wine64-preloader
```
Overriden, like in the official wine packages for Debian.

```
E: wine-staging-i386: usr-share-doc-symlink-without-dependency wine-staging
E: wine-staging-amd64: usr-share-doc-symlink-without-dependency wine-staging
```
Fixed by adding missing `${misc:Depends}` substitution variables to debian/control.

```
W: wine-staging-i386: description-synopsis-starts-with-article
W: wine-staging-amd64: description-synopsis-starts-with-article
W: wine-staging: description-synopsis-starts-with-article
W: wine-staging: extended-description-line-too-long
W: wine-staging: extended-description-line-too-long
```
Updated the package descriptions.

```
W: wine-staging-amd64: postinst-has-useless-call-to-ldconfig
W: wine-staging-amd64: postrm-has-useless-call-to-ldconfig
W: wine-staging-i386: postinst-has-useless-call-to-ldconfig
W: wine-staging-i386: postrm-has-useless-call-to-ldconfig
```
By adding `override_dh_makeshlibs:` to debian/rules the maintainer scripts won't do any calls to ldconfig.

```
E: wine-staging source: build-depends-on-essential-package-without-using-version build-depends: coreutils
E: wine-staging source: build-depends-on-essential-package-without-using-version build-depends: gzip
```
Removed from build dependencies.

```
E: wine-staging: no-copyright-file
W: wine-staging: extra-license-file usr/share/doc/wine-staging/COPYING.LIB.gz
W: wine-staging: extra-license-file usr/share/doc/wine-staging/COPYING.arial
W: wine-staging: extra-license-file usr/share/doc/wine-staging/COPYING.cour.gz
W: wine-staging: extra-license-file usr/share/doc/wine-staging/COPYING.msyh.gz
W: wine-staging: extra-license-file usr/share/doc/wine-staging/LICENSE
```
Removed the license files from  debian/wine-staging.docs and instead a debian/copyright file is now provided.

Other changes in debian/control: bumped standards version, added missing `${misc:Depends}` variables and removed `${shlibs:Depends}` on packages which don't require it. Priority on wine-staging-dbg was changed to "extra" (required for debug packages).

### CODE REVIEW

**Comment by slackner** [comment]
Thanks for your contribution. I've quickly looked over the patches, and most of it should be fine. Nevertheless, we might have to test it a bit. We currently use the same packaging files for basically all Debian and Ubuntu builds, so I am not sure if the version bump causes any problems. I'll report back after some testing.

**Comment by slackner** [comment]
Your changes seem to break our builds for AVLinux (which is basically Debian Squeeze):

```
dpkg-shlibdeps: error: no dependency information found for /build/job/build-masJce/source/debian/tmp/opt/wine-staging/lib/libwine.so.1 (used by debian/wine-staging-i386/opt/wine-staging/lib/wine/cards.dll.so).
dh_shlibdeps: dpkg-shlibdeps -Tdebian/wine-staging-i386.substvars debian/wine-staging-i386/opt/wine-staging/bin/wine [...] returned exit code 2
make[1]: *** [override_dh_shlibdeps] Error 9
make[1]: Leaving directory `/build/job/build-masJce/source'
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
```

Here the full buildlog:
http://cache.fds-team.de/failed-builds/20150323-090124-debian-avlinux-i686-build.log.gz

**Comment by darealshinji** [comment]
That's probably because of the overridden dh_makeshlibs.
Does it work if you change `override_dh_shlibdeps` to this?
```makefile
override_dh_shlibdeps:
ifeq ($(DEB_HOST_ARCH),amd64)
	dh_shlibdeps -Lwine-staging-amd64 -l/opt/wine-staging/lib64/
else
	dh_shlibdeps -Lwine-staging-i386 -l/opt/wine-staging/lib/
endif
```
If it doesn't, removing `override_dh_makeshlibs:` should do it.

**Comment by slackner** [comment]
Still throws errors:
http://cache.fds-team.de/failed-builds/20150323-152443-debian-avlinux-i686-build.log.gz

It might probably be easier to split your changes a bit, starting with those that definitely do not break anything, and afterwards the more risky stuff. Then I can test it separately.

**Comment by darealshinji** [comment]
Yeah, sounds good. I'll do that later and start with the safe changes.

**Comment by darealshinji** [comment]
This can be closed now.

**Pull request closed without merging**
