### PR TITLE
Add patches for d3dadapter.

### PR DESCRIPTION
**Pull request by jobermayr**
Patches are maintained at:
https://github.com/iXit/wine/commits/master

Some background information:
http://www.phoronix.com/scan.php?page=news_item&px=MTgzOTc
https://fedoraproject.org/wiki/Changes/Wine_to_use_mesa_Direct3D
http://www.gearsongallium.com/

### CODE REVIEW

**Comment by slackner** [comment]
Hi,

we also followed the development of this patchset during the last months, and also talked to the people behind this project. In general we have no problem with adding the d3dadapter patchsets, but we would like to get various issues fixed first.

Some of these issues have already been pointed out long time ago, shortly after the "initial version", but are still not fixed, for example that memory allocated with driver internal functions should never be exposed directly to the Windows applications. The whole interface and also the changes to `configure.ac` are very hacky, and should be cleaned up a bit. Also, as long as upstream Wine refuses the inclusion of this patchset, there is no need to split the changes across multiple wine dlls. What we would prefer is a patch similar to the one for adding CSMT support, which adds an additional self-contained dll `d3d9-nine.dll`, that can be selected by everyone who wants to use it. All these ideas have already been told to the developers in the past.

The d3d9 people seemed to be interested in doing these changes, but it doesn't seem to have a very high priority. I can understand that, because its of course more interesting to get new apps/games working, instead of messing around with old code. Nevertheless, since we fear that it will never be cleaned up otherwise, we would like to have that done before we give our okay. So, unfortunately I'll have to reject this patchset for now. As soon as the necessary cleanup is done, we will happily include it.

By the way: Did you manually modify the autogenerated `patchinstall.sh` script? The lines are not ordered alphabetically and the escaping of '(' characters looks unusual. Take a look [here](https://github.com/wine-compholio/wine-staging/wiki/Development#makefile-system) how to configure the patch system so that autogenerated files are updated automatically on every commit.

Regards,
Sebastian

**Comment by Eignar17** [comment]
@slackner the gallium-nine drivers using something free for people who use nvidia go from bad to worse if they used private drivers would be best for the project but only nvdia is it problem

**Comment by EoD** [comment]
Seems like someone is working on at least one of the issues mentioned here: https://github.com/siro20/wine/commit/888e276a865f725652bb1f783f57648073837720

**Comment by slackner** [comment]
I'm aware of that, however as far as I know the changes regarding the inclusion into Wine Staging are not finished yet. A more up-to-date discussion is here btw: https://bugs.wine-staging.com/show_bug.cgi?id=40 (and also takes place in the #d3d9 channel from time to time).

**Pull request closed without merging**
