### PR TITLE
introduce "dummy" backend

### PR DESCRIPTION
**Pull request by rockdrilla**
dummy backend only lists applied patches
no modifications are made to ${DESTDIR}
furthermore, ${DESTDIR} doesn't need to be specified in command line

### CODE REVIEW

**Comment by slackner** [comment]
Hi,

May I ask for what exactly you need such a dummy backend?

If you plan to apply the series with other patch tools, please note that most of them do not support Git binary patches. The Wine Staging patchset contains a bunch of them, mainly in `fonts-Missing_Fonts`.

Currently not a big problem, but there have also been discussions to use autogenerated changes for other parts, besides the patch list and `configure`. For developers a dummy backend might still be useful, but for packagers it would not be the best approach to duplicate all the logic into packaging scripts.

Regards,
Sebastian

**Comment by rockdrilla** [comment]
Hi!

I'm using this backend to generate list & export patches to own Debian source package.
All patching logic is under dpkg-buildpackage's control.
Thanks, I've already noted that quilt doesn't understand git binary patches. :)

PS: i'm sorry for my poor english.

**Comment by slackner** [comment]
>I'm using this backend to generate list & export patches to own Debian source package.
>All patching logic is under dpkg-buildpackage's control.
>Thanks, I've already noted that quilt doesn't understand git binary patches. :)

How do you plan to deal with the binary patches? When they are silently ignored by Quilt you might get build errors (missing files) or a broken/incomplete build. Before adding such a feature, I would like to make sure that the idea actually works. For our own Debian builds, we just use the provided patchinstall.sh script and call it from the `rules` file. With your method there is also no way to generate the patch list, so `wine --patches` will not work as expected.

**Comment by slackner** [comment]
I assume the idea was abandoned, so closing this pull request. As said in the last comment, I am fine with the idea to add such a backend, but I would like to see a valid use-case for it. To my knowledge, the Debian build tools still can not deal with binary patches, and trying to do it anyway would result in a build failure.

**Pull request closed without merging**
