### PR TITLE
Debian packaging: safe changes

### PR DESCRIPTION
**Pull request by darealshinji**
Deleted empty conffiles, added copyright file, removed extra licenses from wine-staging.docs, created source/format and updated the package descriptions.
This should fix the following:
```
W: wine-staging-i386: control-file-is-empty conffiles
W: wine-staging-i386: description-synopsis-starts-with-article
W: wine-staging-amd64: description-synopsis-starts-with-article
W: wine-staging: description-synopsis-starts-with-article
W: wine-staging: extended-description-line-too-long
E: wine-staging: no-copyright-file
W: wine-staging: extra-license-file usr/share/doc/wine-staging/COPYING.LIB.gz
W: wine-staging: extra-license-file usr/share/doc/wine-staging/COPYING.arial
W: wine-staging: extra-license-file usr/share/doc/wine-staging/COPYING.cour.gz
W: wine-staging: extra-license-file usr/share/doc/wine-staging/COPYING.msyh.gz
W: wine-staging: extra-license-file usr/share/doc/wine-staging/LICENSE
```

### CODE REVIEW

**Comment by slackner** [comment]
Looks good to me, and passes compilation on Debian Squeeze and Sid.

@DarkPlayer / @compholio: Could you please test on Ubuntu and give your ack when you are fine with all the changes?

**Comment by compholio** [comment]
@slackner : Don't we need to include those extra license files?

**Comment by slackner** [comment]
@compholio: The license files were moved to debian/copyright in https://github.com/darealshinji/wine-staging/commit/1044ff29818bf85ffc9adf19ba0f29d116786f7b

As far as I know that should be fine, but I'm not sure if its okay that the last sentence of the LGPLv2 / GPL3 license text was modified:

```
+On Debian systems, the complete text of the GNU Library General Public
+License can be found in /usr/share/common-licenses/LGPL-2.1 file.
```

Is that equivalent to the original last part of the license (from a legal perspective I mean)?

**Comment by compholio** [comment]
@slackner This is common behavior in a lot of packages.

**Comment by DarkPlayer** [comment]
I think the debian/copyright file should follow the rules defined by https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/.

I tried to create such a file which you can find at https://dl.dropboxusercontent.com/u/61413222/copyright.
Currently only the apache2 license for the WenQuanYi Micro Hei font is missing (http://wenq.org/wqy2/index.cgi?Apache_License_2.0). If someone wants to add it, feel free to do so. I also need to check if debuild likes it ;-)

**Comment by slackner** [comment]
According to https://www.debian.org/doc/debian-policy/ch-docs.html#s-copyrightfile the use of the machine-readable format is optional. In this case it actually shouldn't be too difficult to use it, and we might even be forced to use it when Ubuntu accepts our packaging request. I would vote for changing it. @DarkPlayer: @compholio: Votes please?

@darealshinji: If the others agree, do you want to adjust your pull request accordingly, or should I just cherry-pick the other changes first?

**Comment by darealshinji** [comment]
I can adjust my PR and use DarkPlayers copyright file plus add the Apache 2 license for the WenQuanYi Micro Hei font.

**Comment by DarkPlayer** [comment]
@darealshinji I already updated the file and added the Apache 2 license, but according to https://lintian.debian.org/tags/copyright-file-contains-full-apache-2-license.html the copyright file shouldn't include the whole license, so feel free to trim it down and redirect to ` /usr/share/common-licenses/Apache-2.0`.

**Comment by darealshinji** [comment]
I've added the new copyright file and mentioned the Apache 2 license.

**Comment by DarkPlayer** [comment]
Now the license is included two times (line 212 and 398) ;-)

**Comment by darealshinji** [comment]
Oh, I didn't see that. I've removed the long version and left the short one.

**Comment by slackner** [comment]
Thanks, merged! :) Now to the more complicated changes, hehe ;)

**Pull request merged**
