### PR TITLE
Debian packaging: remaining fixes

### PR DESCRIPTION
**Pull request by darealshinji**
Bump debhelper compatibility level to 9.
Two important effects are:
 * All of the dh_auto_* debhelper programs and dh set environment variables listed by dpkg-buildflags, unless they are already set.
 * dh_strip puts separated debug symbols in a location based on their build-id (as a side-effect it turns off Lintian's `arch-dependent-file-not-in-arch-specific-directory` error warnings).

For more details see http://manpages.ubuntu.com/manpages/trusty/man7/debhelper.7.html#contenttoc8 or run `man debhelper`.

I've fixed the substitution variables in debian/control which turns off the following warnings during the building:
```
dpkg-gencontrol: warning: Pre-Depends field of package wine-staging-amd64: unknown substitution variable ${misc:Pre-Depends}
dpkg-gencontrol: warning: Pre-Depends field of package wine-staging: unknown substitution variable ${misc:Pre-Depends}
dpkg-gencontrol: warning: package wine-staging: unused substitution variable ${perl:Depends}
dpkg-gencontrol: warning: Pre-Depends field of package wine-staging-dev: unknown substitution variable ${misc:Pre-Depends}
dpkg-gencontrol: warning: Depends field of package wine-staging-dev: unknown substitution variable ${shlibs:Depends}
dpkg-gencontrol: warning: Pre-Depends field of package wine-staging-dbg: unknown substitution variable ${misc:Pre-Depends}
dpkg-gencontrol: warning: Depends field of package wine-staging-dbg: unknown substitution variable ${shlibs:Depends}
```

Priority for the package wine-staging-dbg was set to extra. Fixes `wine-staging-dbg: debug-package-should-be-priority-extra wine-staging-dbg`

The following warnings were overridden:
```
wine-staging-amd64: postinst-has-useless-call-to-ldconfig
wine-staging-amd64: postrm-has-useless-call-to-ldconfig
wine-staging-i386: postinst-has-useless-call-to-ldconfig
wine-staging-i386: postrm-has-useless-call-to-ldconfig
```
This is caused by a bug in debhelper (which for some reason isn't fixed yet). It's because the package contains shared libraries which aren't installed in a system library search path. This could be prevented by overriding the dh_makeshlibs target in debian/rules, but that causes the build to fail. However, a useless call of ldconfig is harmless, so overriding is probably the best solution here.

With these changes is did build for me on Launchpad.

PS: If you want smaller source tarballs, create debian/source/options with the content `compression = bzip2` or `compression = xz`.

### CODE REVIEW

**Comment by slackner** [comment]
Sorry for the delay, we had our bi-weekly release yesterday so I was more busy with preparing the release. Will check your changes later today and report back. Testing on launchpad is definitely nice, but not fully sufficient, Debian Squeeze ships much older build tools, especially version bumps are often a bit critical. ;)

**Comment by slackner** [comment]
It breaks on Debian Squeeze:
http://cache.fds-team.de/failed-builds/20150406-083928-debian-avlinux-i686-build.log.gz

```dh: Sorry, but 8 is the highest compatibility level supported by this debhelper.```

**Comment by darealshinji** [comment]
I didn't know that Squeeze only supports compat level up to 8. I've lowered it, set the buildflags in the configure phase manually and added a Lintian override for the debug package's `arch-dependent-file-not-in-arch-specific-directory` warnings.

**Comment by slackner** [comment]
Sorry for the late reply, I've been very busy during the last week. Your latest version of the patch neither applies (things like the wine-staging-compat symlinks can only be added when you rebase your patch after the point where the corresponding package was added), nor compiles:

```
# Create compatibility symlinks
mkdir -p debian/wine-compholio/opt/wine-compholio/bin
mkdir -p debian/wine-staging-compat/usr/bin
for _file in $(ls "debian/wine-staging/opt/wine-staging/bin"); do ln -s "../../wine-staging/bin/$_file" "debian/wine-compholio/opt/wine-compholio/bin/$_file"; ln -s "../../wine-staging/bin/$_file" "debian/wine-staging-compat/usr/bin/$_file";; done
/bin/sh: -c: line 0: syntax error near unexpected token `;;'
/bin/sh: -c: line 0: `for _file in $(ls "debian/wine-staging/opt/wine-staging/bin"); do ln -s "../../wine-staging/bin/$_file" "debian/wine-compholio/opt/wine-compholio/bin/$_file"; ln -s "../../wine-staging/bin/$_file" "debian/wine-staging-compat/usr/bin/$_file";; done'
make[1]: *** [override_dh_install] Error 1
```

Besides that I've tried to find out why you did some of the changes, and its not really clear to me if they are really necessary.
* According to https://wiki.debian.org/Multiarch/Implementation the line `Pre-Depends: ${misc:Pre-Depends}` should be added to every package providing a shared library. Wine for example provides `libwine.so` which will be used by all applications compiled with `winegcc`. Are you sure that its safe to remove it?
* Why is it necessary to manually deal with CFLAGS and LDFLAGS? Are those variables not set by default? If not then the change is a bit risky, because Wine easily breaks / doesn't work properly with wrong CFLAGS, for example when stack protector is enforced.

I'll leave it up to you if you want to create new separate pull requests for some of these changes, or if I should cherry-pick corresponding commits which look good to me, and afterwards we discuss about the rest.

**Comment by darealshinji** [comment]
The `${misc:Pre-Depends}` variable is not used since nothing is installed into a multi-arch directory (`/usr/lib/*-linux-gnu`). However, this only stops a warning that appears during the build, so you don't have to remove it if you don't want to.

As for the buildflags: on compat level 9 the dpkg buildflags are automatically added (run `dpkg-buildflags` in a console to see them). On compat 8 this isn't done. Normally adding them is recommended and not a problem, but in some cases leaving them or replacing them with something else is required. Remove the custom flags if that's the better solution for Wine.

The remaining changes in debian/rules are meant to reduce code. The compatibility symlink stuff didn't work because I accidentally added a `;` where there shouldn't be one. Removing the `;` after `$(compatlinks)` in every instance of `do $(compatlinks); done` in debian/rules should do it.

> […] or if I should cherry-pick corresponding commits which look good to me, and afterwards we discuss about the rest.

This.

**Comment by qwertychouskie** [comment]
Any updates on this?

**Comment by slackner** [comment]
There are no Debian packaging files in the Staging repository anymore, so this can be closed.

**Pull request closed without merging**
