### PR TITLE
Implement shader parameter caching 

### PR DESCRIPTION
**Pull request by zefkerr**
Hi! Thanks to the new developers Wine Staging that you began to continue this important project and did not let it die. And thank to Michael and Sebastian for all that great contribution to the development of Wine, what they did.

Michael Müller began creating patches for implementation of shader parameter caching, but, as we all already know, unfortunately, he stopped further work on the Wine Staging project:
https://wine-staging.com/news/2018-02-17-future-wine-staging.html

Therefore, unfortunately, he did not have time to finish work on these patches.
But I'm sure that the completion, rebase to modern version of Wine Staging and then addition of these patches will give a great improvement to the smoothness of the games and solve the problem with stuttering in Wine games, especially in combination with new impressive Wine-PBA patches that are developing now, which really increase FPS in Wine games by ~30%-60%:
https://github.com/acomminos/wine-pba
https://comminos.com/posts/2018-02-21-wined3d-profiling.html

Find these Michael Müller's shader parameter caching patches and learn all the details you can at this link:
https://dev.wine-staging.com/patches/204

Tell me, please, what do you think about this?
And will you take up this matter?
And will we ever see these patches officially included in the Wine Staging upstream or Wine upstream?
If you need some help testing these patches, then I and maybe some other members of the Wine Community are ready to help you with this.

### CODE REVIEW

**Comment by Thaodan** [comment]
Is there a rebases version for wine 3.3?

**Comment by qwertychouskie** [comment]
@Kerrung I think you meant to open this at https://github.com/wine-staging/wine-staging, this repo is the old abandoned one.

**Comment by Kerrung** [comment]
> @qwertychouskie: @Kerrung I think you meant to open this at https://github.com/wine-staging/wine-staging, this repo is the old abandoned one.

I tried to create it exactly in the new Wine Staging repository, but Github unfortunately automatically redirected it here. After that, I tried to create it again in a new repository, but unfortunately I did not succeed and this time too, because Github unfortunately automatically redirected it here again, because this is the original repository, and the new Wine Staging repository is just the fork of this original repo.
Tell me please if you know the solution to this issue. You can try to create any pull request yourself in the new W.S. repository, but most likely you will also encounter such a issue.
Thank you.

**Comment by qwertychouskie** [comment]
@Kerrung https://bugs.winehq.org/enter_bug.cgi?product=Wine-staging is probably the right place.

**Comment by Kerrung** [comment]
> qwertychouskie @Kerrung https://bugs.winehq.org/enter_bug.cgi?product=Wine-staging is probably the right place.

Thank you!

**Comment by sskras** [comment]
Why everything is getting flooded into PR #338 ?  It looks like a misconfiguration of Github bug to me.
What if this PR gets closed?

**Comment by qwertychouskie** [comment]
@Kerrung Can you close this PR?  It is flooding users subscribed to this repo with commit messages for https://github.com/wine-staging/wine-staging.

**Comment by mirh** [comment]
Can this be closed then?
And is the shader parameter caching patch still needed and available somewhere?

**Pull request closed without merging**
