### PR TITLE
Added patches for msstyles v4 support in uxtheme.

### PR DESCRIPTION
**Pull request by maharmstone**
Sorry, I've just noticed a bug in patch 15 - the LOGFONT needs to be memset first, MSSTYLES_GetFont doesn't do it. If a corrupted LOGFONT gets into the WindowMetrics key, it can cause all GUI applications to crash on startup.

### CODE REVIEW

**Comment by slackner** [comment]
Sorry for the delay, I didn't have much time recently to work on Wine. There are still a couple of issues with your patch, and originally I was planning to fix them myself, but its probably faster to give you a chance to fix it:

* I am still a bit unhappy about the first two patches. The code to enumerate those files works as expected, but looks very ugly and unnecessarily complicated. It might be useful to define helper functions for some things, like adding files to the lists. Also, a lot of the string operations could probably be replaced with format strings.

* When testing with german locale *.mui files, the code does not properly enumerate all the color schemes. The last char of the color name is missing, and all additional styles which are present on Windows are missing in Wine. Does it work properly with other locales?

**Comment by maharmstone** [comment]
Not to worry, thank you for looking at it.

Yes, you're right about the MUI stuff - I really need to implement the proper functions.

Could you please e-mail me the German files? I only have the English ones to test with. I remember having to truncate the last character of the strings, and I wasn't entirely clear why... For Windows 7 at least, it's my understanding that there's only one colour and style per file, given that they removed the comboboxes for colour etc. present in XP.

**Comment by davispuh** [comment]
Ping/Update?

This would be cool feature. I tested that it kinda works but seems even with this PR it's not fully implemented as a lot of things are not styled like buttons, scrollbars, menus and maybe other things.

**Comment by maharmstone** [comment]
I've been busy with other stuff, to be honest - I'll get round it to it eventually. The main problem is that the new themes rely on MUI, which involves kernel-space stuff and isn't terribly well-documented. Menus and non-client scrollbars are implemented on Windows by uxtheme hooking user32, but I've not yet been able to replicate this in a way upstream is happy with.

Are you trying that with a Windows 10 theme, by any chance? They've added a few new things, and I've been waiting for the official release before investigating properly.

**Comment by davispuh** [comment]
No, I didn't tried with 10 but with default Win 8.1 aero (and aerolite) theme (from `%windir%\Resources\Themes\`)

**Comment by qwertychouskie** [comment]
Any updates on this?

**Comment by slackner** [comment]
I'm not sure if Mark is still working on this, so I'm closing this pull request for now.

**Pull request closed without merging**
